
name: CI-CD

# Eventos que van a disparar el workflow
on:
  # Evento que se dispara cuando se hace un push al repositorio, en la rama main
  push:
    branches: [ "main" ]
  # Evento que se dispara cuando se hace un pull request al repositorio, en la rama main
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

# Jobs que se van a ejecutar
jobs:

  # Job que se va a ejecutar en este caso se llama build
  build:
    # Es el runner que se va a utilizar
    runs-on: ubuntu-latest

    # Pasos que se van a ejecutar
    steps:
      # Se clona el repositorio, esto se convierte en un paso y a su ves es un action
      - uses: actions/checkout@v3

      # Se ejecuta un script
      - name: Run a one-line script
        run: echo Hello, world!

      # Se ejecuta un script de varias lineas, para ello el operador |
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  # Job que se va a ejecutar en este caso se llama test
  test:
    # Es el runner que se va a utilizar
    runs-on: ubuntu-latest

    # Pasos que se van a ejecutar
    steps:
      # Se clona el repositorio, esto se convierte en un paso y a su ves es un action
      - uses: actions/checkout@v3

      # Se ejecuta un script
      - name: Run a one-line script
        run: echo Hello, world!

      # Se ejecuta un script de varias lineas, para ello el operador |
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy:
    # Es el runner que se va a utilizar
    runs-on: ubuntu-latest

    # Pasos que se van a ejecutar
    steps:
      # Se clona el repositorio, esto se convierte en un paso y a su ves es un action
      - uses: actions/checkout@v3

      # Se ejecuta un script
      - name: Run a one-line script
        run: echo Hello, world!

      # Se ejecuta un script de varias lineas, para ello el operador |
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
